# 0x05. Python - Exceptions

In this project, I learned handling errors and exceptions in Python with `try` and `except`.

## Function Prototypes
Prototypes for functions written in this project:

| File                             | Prototype                                               |
| -------------------------------- | ------------------------------------------------------- |
| `0-safe_print_list.py`           | `def safe_print_list(my_list=[], x=0):`                 |
| `1-safe_print_integer.py`        | `def safe_print_integer(value):`                        |
| `2-safe_print_list_integers.py`  | `def safe_print_list_integers(my_list=[], x=0):`        |
| `3-safe_print_division.py`       | `def safe_print_division(a, b):`                        |
| `4-list_division.py`             | `def list_division(my_list_1, my_list_2, list_length):` |
| `5-raise_exception.py`           | `def raise_exception():`                                |
| `6-raise_exception_msg.py`       | `def raise_exception_msg(message=""):`                  |

## Tasks
* **Safe list printing**
  * `0-safe_print_list.py`: Prints `x` elements of a list on the same line, 
followed by a new line.
  * The parameter `x` represents the number of elements to print - can be 
bigger than the length of `my_list`.
  * Returns the real number of elements printed.
  * Using `try: / except:` and without importing modules.

### [1. Safe printing of an integers list](./1-safe_print_integer.py)
* Write a function that prints an integer with "{:d}".format().


### [2. Print and count integers](./2-safe_print_list_integers.py)
* Write a function that prints the first x elements of a list and only integers.


### [3. Integers division with debug](./3-safe_print_division.py)
* Write a function that divides 2 integers and prints the result.


### [4. Divide a list](./4-list_division.py)
* Write a function that divides element by element 2 lists.


### [5. Raise exception](./5-raise_exception.py)
* Write a function that raises a type exception.


### [6. Raise a message](./6-raise_exception_msg.py)
* Write a function that raises a name exception with a message.

---

## Author
* **Brennan D Baraban** - [bdbaraban](https://github.com/bdbaraban)
